#remote_theme: sighingnow/jekyll-gitbook
title: Customized R Interaction Plots using Mplus Output
description: R vignettes
syntax_highlighter_style: colorful
#toc:
#    disabled: false
#theme: just-the-docs
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
