#remote_theme: sighingnow/jekyll-gitbook
title: Customized R Interaction Plots using Mplus Output
description: R vignettes
syntax_highlighter_style: colorful
toc:
    enabled: false
theme: just-the-docs
